// Copyright 2024 Cavon
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once


// WS2812
#ifdef RGB_MATRIX_ENABLE
#  define WS2812_DI_PIN GP20
#ifdef SPLIT_KEYBOARD
#  define RGB_MATRIX_LED_COUNT 48
#  define RGB_MATRIX_SPLIT { 24, 24 }
#else
#  define RGB_MATRIX_LED_COUNT 24
#endif // SPLIT_KEYBOARD

#  define ENABLE_RGB_MATRIX_ALPHAS_MODS
#  define ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
#  define ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
#  define ENABLE_RGB_MATRIX_BREATHING
#  define ENABLE_RGB_MATRIX_BAND_SAT
#  define ENABLE_RGB_MATRIX_BAND_VAL
#  define ENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
#  define ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
#  define ENABLE_RGB_MATRIX_BAND_SPIRAL_SAT
#  define ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
#  define ENABLE_RGB_MATRIX_CYCLE_ALL
#  define ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#  define ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
#  define ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#  define ENABLE_RGB_MATRIX_CYCLE_OUT_IN
#  define ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#  define ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
#  define ENABLE_RGB_MATRIX_CYCLE_SPIRAL
#  define ENABLE_RGB_MATRIX_DUAL_BEACON
#  define ENABLE_RGB_MATRIX_RAINBOW_BEACON
#  define ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS
#  define ENABLE_RGB_MATRIX_FLOWER_BLOOMING
#  define ENABLE_RGB_MATRIX_RAINDROPS
#  define ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#  define ENABLE_RGB_MATRIX_HUE_BREATHING
#  define ENABLE_RGB_MATRIX_HUE_PENDULUM
#  define ENABLE_RGB_MATRIX_HUE_WAVE
#  define ENABLE_RGB_MATRIX_PIXEL_FRACTAL
#  define ENABLE_RGB_MATRIX_PIXEL_FLOW
#  define ENABLE_RGB_MATRIX_PIXEL_RAIN
#  define ENABLE_RGB_MATRIX_STARLIGHT
#  define ENABLE_RGB_MATRIX_STARLIGHT_DUAL_HUE
#  define ENABLE_RGB_MATRIX_STARLIGHT_DUAL_SAT
#  define ENABLE_RGB_MATRIX_RIVERFLOW

#  define ENABLE_RGB_MATRIX_TYPING_HEATMAP
#  define ENABLE_RGB_MATRIX_DIGITAL_RAIN

#  define ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#  define ENABLE_RGB_MATRIX_SOLID_REACTIVE
#  define ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
#  define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
#  define ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
#  define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
#  define ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
#  define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
#  define ENABLE_RGB_MATRIX_SPLASH
#  define ENABLE_RGB_MATRIX_MULTISPLASH
#  define ENABLE_RGB_MATRIX_SOLID_SPLASH
#  define ENABLE_RGB_MATRIX_SOLID_MULTISPLASH

#  define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_PIXEL_FLOW
#  define RGB_MATRIX_DEFAULT_HUE 0
#  define RGB_MATRIX_DEFAULT_SAT 200
#  define RGB_MATRIX_DEFAULT_ON true
#  define RGB_MATRIX_DEFAULT_VAL 127
#  define RGB_MATRIX_DEFAULT_SPD 127
#endif // RGB_MATRIX_ENABLE


// Boot Magix Lite
#ifdef BOOTMAGIC_ENABLE
#  define BOOTMAGIC_LITE_ROW 0
#  define BOOTMAGIC_LITE_COLUMN 0
// #ifdef SPLIT_KEYBOARD
// #  define BOOTMAGIC_LITE_ROW_RIGHT 4
// #  define BOOTMAGIC_LITE_COLUMN_RIGHT 5
#  define BOOTMAGIC_LITE_ROW_RIGHT 0
#  define BOOTMAGIC_LITE_COLUMN_RIGHT 0
// #endif // SPLIT_KEYBOARD
#endif // BOOTMAGIC_ENABLE


// OLED_ENABLE
#ifdef OLED_ENABLE
#  define I2C1_SDA_PIN           GP26
#  define I2C1_SCL_PIN           GP27
#  define OLED_DISPLAY_ADDRESS   0x3C
// #define OLED_DISPLAY_CUSTOM
// #define OLED_DISPLAY_WIDTH     128
// #define OLED_DISPLAY_HEIGHT    32
// #define OLED_MATRIX_SIZE       512
// #define OLED_BLOCK_TYPE        uint16_t
#endif // OLED_ENABLE


// Audio
#ifdef AUDIO_ENABLE
#  define AUDIO_PIN GP21
#  define AUDIO_PWM_DRIVER PWMD2
#  define AUDIO_PWM_CHANNEL RP2040_PWM_CHANNEL_B
#  define AUDIO_INIT_DELAY
// #  define AUDIO_CLICKY
#  define AUDIO_VOICES
#endif // AUDIO_ENABLE

// Split Keyboard
// #ifdef SPLIT_KEYBOARD
#  define EE_HANDS
#  define SPLIT_TRANSPORT_MIRROR
#  define SPLIT_LAYER_STATE_ENABLE
#  define SPLIT_LED_STATE_ENABLE
#  define SPLIT_MODS_ENABLE
#  define SPLIT_WPM_ENABLE
#  define SPLIT_OLED_ENABLE
#  define SPLIT_ACTIVITY_ENABLE
#  define RGBLIGHT_SPLIT
#  define RGBLED_SPLIT { 24, 24 }
#  define SPLIT_USB_DETECT
// #endif // SPLIT_KEYBOARD

// Serial
// #define SERIAL_USART_DRIVER SIOD1
// #define SERIAL_PIO_USE_PIO1
#define RP_SERIAL_USE_UART1
#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_TX_PIN GP4
#define SERIAL_USART_RX_PIN GP5
#define SERIAL_USART_PIN_SWAP

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESETy
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 1000U
