// Copyright 2024 Cavon
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

// WS2812
#ifdef RGB_MATRIX_ENABLE
#  define WS2812_DI_PIN GP4
#  define RGB_MATRIX_LED_COUNT 74
#  define RGB_MATRIX_SPLIT { 37, 37 }

#  define ENABLE_RGB_MATRIX_ALPHAS_MODS
#  define ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
#  define ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
#  define ENABLE_RGB_MATRIX_BREATHING
#  define ENABLE_RGB_MATRIX_BAND_SAT
#  define ENABLE_RGB_MATRIX_BAND_VAL
#  define ENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
#  define ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
#  define ENABLE_RGB_MATRIX_BAND_SPIRAL_SAT
#  define ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
#  define ENABLE_RGB_MATRIX_CYCLE_ALL
#  define ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#  define ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
#  define ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#  define ENABLE_RGB_MATRIX_CYCLE_OUT_IN
#  define ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#  define ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
#  define ENABLE_RGB_MATRIX_CYCLE_SPIRAL
#  define ENABLE_RGB_MATRIX_DUAL_BEACON
#  define ENABLE_RGB_MATRIX_RAINBOW_BEACON
#  define ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS
#  define ENABLE_RGB_MATRIX_FLOWER_BLOOMING
#  define ENABLE_RGB_MATRIX_RAINDROPS
#  define ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#  define ENABLE_RGB_MATRIX_HUE_BREATHING
#  define ENABLE_RGB_MATRIX_HUE_PENDULUM
#  define ENABLE_RGB_MATRIX_HUE_WAVE
#  define ENABLE_RGB_MATRIX_PIXEL_FRACTAL
#  define ENABLE_RGB_MATRIX_PIXEL_FLOW
#  define ENABLE_RGB_MATRIX_PIXEL_RAIN
#  define ENABLE_RGB_MATRIX_STARLIGHT
#  define ENABLE_RGB_MATRIX_STARLIGHT_DUAL_HUE
#  define ENABLE_RGB_MATRIX_STARLIGHT_DUAL_SAT
#  define ENABLE_RGB_MATRIX_RIVERFLOW

#  define ENABLE_RGB_MATRIX_TYPING_HEATMAP
#  define ENABLE_RGB_MATRIX_DIGITAL_RAIN

#  define ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#  define ENABLE_RGB_MATRIX_SOLID_REACTIVE
#  define ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
#  define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
#  define ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
#  define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
#  define ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
#  define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
#  define ENABLE_RGB_MATRIX_SPLASH
#  define ENABLE_RGB_MATRIX_MULTISPLASH
#  define ENABLE_RGB_MATRIX_SOLID_SPLASH
#  define ENABLE_RGB_MATRIX_SOLID_MULTISPLASH

#  define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_SOLID_COLOR
#  define RGB_MATRIX_DEFAULT_HUE 0
#  define RGB_MATRIX_DEFAULT_SAT 200
#  define RGB_MATRIX_DEFAULT_ON true
#  define RGB_MATRIX_DEFAULT_VAL 127
#  define RGB_MATRIX_DEFAULT_SPD 127
#endif // RGB_MATRIX_ENABLE


// Boot Magix Lite
#ifdef BOOTMAGIC_ENABLE
#  define BOOTMAGIC_LITE_ROW 0
#  define BOOTMAGIC_LITE_COLUMN 0
#ifdef SPLIT_KEYBOARD
#  define BOOTMAGIC_LITE_ROW_RIGHT 8
#  define BOOTMAGIC_LITE_COLUMN_RIGHT 0
#endif // SPLIT_KEYBOARD
#endif // BOOTMAGIC_ENABLE

// Audio
#ifdef AUDIO_ENABLE
#  define AUDIO_PIN GP13
#  define AUDIO_PWM_DRIVER PWMD6
#  define AUDIO_PWM_CHANNEL RP2040_PWM_CHANNEL_B
#  define AUDIO_INIT_DELAY
// #  define AUDIO_CLICKY
#  define AUDIO_VOICES
#endif // AUDIO_ENABLE

// Split Keyboard
// #ifdef SPLIT_KEYBOARD
#  define SPLIT_HAND_PIN GP8
#  define SPLIT_TRANSPORT_MIRROR
#  define SPLIT_LAYER_STATE_ENABLE
#  define SPLIT_LED_STATE_ENABLE
#  define SPLIT_POINTING_ENABLE
#  define SPLIT_ENCODERS_ENABLE
#  define SPLIT_MODS_ENABLE
#  define SPLIT_WPM_ENABLE
#  define SPLIT_ACTIVITY_ENABLE
#  define RGBLIGHT_SPLIT
#  define RGBLED_SPLIT { 37, 37 }
#  define SPLIT_USB_DETECT
// #endif // SPLIT_KEYBOARD

// Serial
#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_TX_PIN GP0
#define SERIAL_USART_RX_PIN GP1
#define SERIAL_USART_PIN_SWAP

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESETy
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 1000U

// Encoder
#ifdef ENCODER_ENABLE
#define ENCODERS_PAD_A { GP29 }
#define ENCODERS_PAD_B { GP28 }
#define ENCODER_RESOLUTIONS { 4 }
// // // #define ENCODER_DIRECTION_FLIP
// #define ENCODERS_PAD_A_RIGHT { }
// #define ENCODERS_PAD_B_RIGHT { }
// #define ENCODER_RESOLUTIONS_RIGHT { }

// #define ENCODERS_PAD_A { }
// #define ENCODERS_PAD_B { }
// #define ENCODER_RESOLUTIONS { }
// #define ENCODERS_PAD_A_RIGHT { GP29 }
// #define ENCODERS_PAD_B_RIGHT { GP28 }
// #define ENCODER_RESOLUTIONS_RIGHT { 4 }
#endif // ENCODER_ENABLE

// Dip Switch
// #define DIP_SWITCH_PINS { GP9, GP10, GP11 }
// #define DIP_SWITCH_MATRIX_GRID { {10,0}, {10,1}, {10,2} }
// #define DIP_SWITCH_MATRIX_GRID_RIGHT { {10,3}, {10,4}, {10,5} }

// Pointer Device
#ifdef POINTING_DEVICE_ENABLE
#define ANALOG_JOYSTICK_X_AXIS_PIN GP28
#define ANALOG_JOYSTICK_Y_AXIS_PIN GP29
// #define ANALOG_JOYSTICK_AXIS_MIN 200
// #define ANALOG_JOYSTICK_AXIS_MAX 1024-ANALOG_JOYSTICK_AXIS_MIN
// #define ANALOG_JOYSTICK_AUTO_AXIS
#define ANALOG_JOYSTICK_SPEED_REGULATOR 5
// #define MOUSE_EXTENDED_REPORT
#define ANALOG_JOYSTICK_WEIGHTS {0,2,4,5,7,8,9,10,12,13,14,15,15,16,17,18,18,19,19,20,20,21,21,21,22,22,22,22,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,24,24,24,24,24,24,25,25,25,26,26,26,27,28,28,29,29,30,31,32,33,34,35,36,37,38,40,41,43,44,46,48,49,51,53,56,58,60,62,65,68,70,73,76,79,82,85,89,92,96,100}
// #define ANALOG_JOYSTICK_READ_INTERVAL 10
// #define ANALOG_JOYSTICK_SPEED_MAX 2
// #define ANALOG_JOYSTICK_CLICK_PIN
// #define ANALOG_JOYSTICK_WEIGHTS
// #define ANALOG_JOYSTICK_CUTOF
#define POINTING_DEVICE_RIGHT
// #define POINTING_DEVICE_ROTATION_90
// #define POINTING_DEVICE_ROTATION_180
// #define POINTING_DEVICE_ROTATION_270
// #define POINTING_DEVICE_INVERT_X
#define POINTING_DEVICE_INVERT_Y
#endif // POINTING_DEVICE_ENABLE
