// Copyright 2024 Cavon
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

// Boot Magix Lite
#ifdef BOOTMAGIC_ENABLE
#  define BOOTMAGIC_LITE_ROW 0
#  define BOOTMAGIC_LITE_COLUMN 0
#endif // BOOTMAGIC_ENABLE

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESETy
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 1000U

// Pointer Device
#ifdef POINTING_DEVICE_ENABLE
#define PMW33XX_CS_PIN GP17
#define PMW33XX_CPI 1000
#define PMW33XX_CLOCK_SPEED 2000000
#define PMW33XX_LIFTOFF_DISTANCE 0x02
#define ROTATIONAL_TRANSFORM_ANGLE 0 // +/- 127
// #define POINTING_DEVICE_INVERT_Y
#define POINTING_DEVICE_INVERT_X
#define POINTING_DEVICE_ROTATION_90
#endif // POINTING_DEVICE_ENABLE


/* ChibiOS SPI definitions */
#define SPI_DRIVER SPID0
#define SPI_SCK_PIN GP18
#define SPI_MOSI_PIN GP19
#define SPI_MISO_PIN GP16

/* Via Setting */
#define VIA_EEPROM_CUSTOM_CONFIG_SIZE 31
